register/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('captcha/', include('captcha.urls')),
    path("", include("user.urls"))
]

user/urls.py
from django.urls import path
from . import views


app_name="user"

urlpatterns = [
    path('', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('hello/', views.hello, name='hello'),
    path('register/', views.sign_up, name='register'),
    path('confirm/<token>', views.confirm, name='confirm'),
    path('forgot_confirm/<token>', views.forgot_confirm, name='forgot_confirm'),
    path('retake-password/', views.retake_password, name='retake-password'),
    path('forgot/', views.forgot, name='forgot')
]

user/models.py
from django.db import models
from django.conf import settings
from itsdangerous import TimedJSONWebSignatureSerializer as ser
from django.shortcuts import reverse

import datetime


class User(models.Model):
    """用户模型"""

    # 用户ID
    _id = models.IntegerField(auto_created=True, primary_key=True)
    # 电子邮箱地址
    email = models.CharField(unique=True, max_length=200)
    # 用户昵称
    username = models.CharField(unique=True, max_length=200)
    # 哈希后的密码
    password_hash = models.CharField(max_length=200)
    # 新增日期
    increase = models.DateTimeField(auto_now_add=True)
    # token
    confirmrd = models.BooleanField(default=False)

    def generate_token(self, email, expiration=3600):
        s = ser(secret_key=settings.SECRET_KEY, expires_in=expiration)
        token = str(s.dumps({"confirm": email}), encoding="utf8")
        return token

    def confirm(self, email, token):
        s = ser(secret_key=settings.SECRET_KEY)
        try:
            data = s.loads(token)
        except :
            return False
        if data.get("confirm") != email:
            return False
        self.confirmed = True
        self.save()
        return True

    def get_absolute_url(self, token):
        return reverse("user:confirm", args=[token])

    def get_forgot_absolute_url(self, token):
        return reverse("user:forgot_confirm", args=[token])

    def __str__(self):
        return self.username

user/forms.py
"""
注册和登录表单
"""
from django import forms
from captcha.fields import CaptchaField


class LoginForm(forms.Form):
    """登录表单"""

    # 用户邮箱
    email = forms.EmailField()
    # 密码
    password = forms.CharField(widget=forms.PasswordInput())

    captcha = CaptchaField(label='验证码')


class RegistrationForm(forms.Form):
    """注册新用户表单"""

    # 邮箱
    email = forms.EmailField()
    # 用户名
    username = forms.CharField()
    # 密码
    password = forms.CharField(widget=forms.PasswordInput())
    # 二次输入密码
    password2 = forms.CharField(widget=forms.PasswordInput())


class RetakePassword(forms.Form):
    """修改密码"""

    # 密码
    password = forms.CharField(widget=forms.PasswordInput())
    # 二次输入密码
    password2 = forms.CharField(widget=forms.PasswordInput())
    # 验证码
    captcha = CaptchaField(label='验证码')


class Forgot(forms.Form):
    """忘记密码"""

    # 电子邮箱地址
    email = forms.EmailField()


class ForgotRetake(forms.Form):
    """验证邮箱后重新设置密码"""

    # email
    email = forms.EmailField()
    # 密码
    password = forms.CharField(widget=forms.PasswordInput())
    # 二次输入密码
    password2 = forms.CharField(widget=forms.PasswordInput())
    # 验证码
    captcha = CaptchaField(label='验证码')

user/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib import messages
from django.core.mail import send_mail
from threading import Thread

from .forms import LoginForm, RegistrationForm, RetakePassword, Forgot, ForgotRetake
from .models import User
from utils.send_email import send_email
from utils.password_hash import hash_password, check_password


"""
messages.debug(request, '%s SQL statements were executed.' % count)
messages.info(request, 'Three credits remain in your account.')
messages.success(request, 'Profile details updated.')
messages.warning(request, 'Your account expires in three days.')
messages.error(request, 'Document deleted.')
"""


def hello(request):
    """欢迎页面"""

    return render(request, "user/hello.html")


def logout(request):
    """登出用户"""

    if not request.session.get('is_login', None):
        return redirect("user:login")
    request.session.flush()
    return redirect("user:login")


def login(request):
    """登录用户"""

    if request.session.get('is_login', None):
        return redirect("user:hello")

    form = LoginForm(request.POST)

    if request.method == "POST":
        if form.is_valid():
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password')
            try:
                user = User.objects.get(email=email)
            except:
                messages.warning(request, '用户不存在')
                return render(request, 'user/login.html', context={"form": form})
            if check_password(password, user.password_hash):
                request.session['is_login'] = True
                request.session['user_email'] = user.email
                request.session['user_name'] = user.username
                return redirect('user:hello')
            else:
                messages.warning(request, '密码错误')
                return render(request, 'user/login.html', context={"form": form})

    return render(request, "user/login.html", context={"form": form})


def sign_up(request):
    """注册新用户"""

    form = RegistrationForm(request.POST)
    if request.method == "POST":
        if form.is_valid():
            email = form.cleaned_data["email"]
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            password2 = form.cleaned_data["password2"]
            if password == password2:
                u = User(email=email, username=username,
                         password_hash=hash_password(password))
                token = u.generate_token(email)
                link = request.build_absolute_uri(u.get_absolute_url(token))
                u.save()
                # 发送认证邮件
                thr = Thread(target=send_email, args=[email, link])
                thr.start()
                messages.success(request, '注册成功，请及时查收确认邮件！')
                return redirect("user:login")
            else:
                messages.warning(request, '请检查两次输入密码是否一致！')
                return redirect("user:register")

    return render(request, "user/signup.html", context={"form": form})


def confirm(request, token):
    """新用户注册 邮件验证"""
    if not request.session.get('is_login', None):
        return redirect("user:login")
    email = request.session['user_email']
    user = User.objects.get(email=email)
    if user.confirmrd:
        messages.warning(request, '已经验证过！')
        return redirect("user:hello")
    else:
        if user.confirm(email=email, token=bytes(token, encoding="utf8")):
            user.confirmrd = True
            user.save()
            messages.success(request, '已验证')
            return redirect("user:hello")
        else:
            messages.warning(request, '认证失败')
            return redirect("user:hello")


def forgot_confirm(request, token):
    """忘记密码 邮件验证"""
    form = ForgotRetake(request.POST)

    if request.method == "POST":
        if form.is_valid():
            email = form.cleaned_data["email"]
            password = form.cleaned_data["password"]
            password2 = form.cleaned_data["password2"]
            try:
                # 用户存在
                u = User.objects.get(email=email)
                if (password == password2) and (u.confirm(email=email, token=bytes(token, encoding="utf8"))):
                    u = User.objects.get(email=email)
                    u.password_hash = hash_password(password)
                    u.save()
                    messages.success(request, '密码修改成功！请重新登录')
                    request.session.flush()
                    return redirect("user:login")
                else:
                    messages.warning(request, '您的输入有误，请重试！')
                    return redirect("user:forgot")
            except User.DoesNotExist:
                # 用户不存在
                messages.warning(request, '用户不存在！')
                return redirect("user:forgot")
    return render(request, "user/forgot_retake.html", context={"form": form, "token": token})


def retake_password(request):
    """修改密码"""

    form = RetakePassword(request.POST)
    if not request.session['is_login']:
        return redirect("user:login")

    if request.method == "POST":
        if form.is_valid():
            password = form.cleaned_data["password"]
            password2 = form.cleaned_data["password2"]
            if password == password2:
                u = User.objects.get(email=request.session['user_email'])
                u.password_hash = hash_password(password)
                u.save()
                messages.success(request, '密码修改成功！请重新登录')
                request.session.flush()
                return redirect("user:login")

    return render(request, "user/retakepassword.html", context={"form": form})


def forgot(request):
    """忘记密码"""

    form = Forgot(request.POST)
    if request.method == "POST":
        if form.is_valid():
            email = form.cleaned_data["email"]
            try:
                # 用户存在
                u = User.objects.get(email=email)
                token = u.generate_token(email)
                link = request.build_absolute_uri(u.get_forgot_absolute_url(token))
                # 发送认证邮件
                thr = Thread(target=send_email, args=[email, link, "forgot"])
                thr.start()
                messages.success(request, '邮件已发送，请及时查收！')
                return redirect("user:login")
            except User.DoesNotExist:
                # 用户不存在
                messages.warning(request, '用户不存在！')
                return redirect("user:forgot")
    return render(request, "user/forgot.html", context={"form": form})

user/templates/user/forgot.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
忘记密码
{% endblock title %}

{% block main %}
<h1>忘记密码</h1>
<hr />
<form action="{% url 'user:forgot' %}" method="post">
	<div class="form-group">
		<div class="form-group">
			{% csrf_token %}
		</div>
		<label for="{{ form.email.id_for_label }}">电子邮件：</label>
		<div class="form-group">
			{{ form.email }}
		</div>
		<input type="submit" class="btn btn-primary" value="提交">
</form>
{% endblock main %}

user/templates/user/forgot_retake.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
重设密码
{% endblock title %}

{% block main %}
<h1>重设密码</h1>
<hr />
<form action="{% url 'user:forgot_confirm' token %}" method="post">
	<div class="form-group">
		<div class="form-group">
			{% csrf_token %}
		</div>
		<label for="{{ form.email.id_for_label }}">电子邮件：</label>
		<div class="form-group">
			{{ form.email }}
        </div>
        <label for="{{ form.password.id_for_label }}">新密码：</label>
		<div class="form-group">
			{{ form.password }}
		</div>
		<label for="{{ form.password2.id_for_label }}">请再输入一次：</label>
		<div class="form-group">
			{{ form.password2 }}
        </div>
        <label for="{{ form.captcha.id_for_label }}">验证码：</label>
		<div class="form-group">
			{{ form.captcha }}
		</div>
		<input type="submit" class="btn btn-primary" value="提交">
</form>
{% endblock main %}

user/templates/user/hello.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
登录
{% endblock title %}

{% block main %}
<h1>欢迎你，{{ request.session.user_name }}</h1>
<hr />
<a href="{% url 'user:retake-password' %}" class="btn btn-danger">修改密码</a>
<a href="{% url 'user:logout' %}" class="btn btn-info">登出</a>
{% endblock main %}

user/templates/user/login.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
登录
{% endblock title %}

{% block main %}
<h1>登录</h1>
<hr />
<form action="/" method="post">
	<div class="form-group">
		<div class="form-group">
			{% csrf_token %}
		</div>
		<label for="{{ form.email.id_for_label }}">电子邮件：</label>
		<div class="form-group">
			{{ form.email }}
		</div>
		<label for="{{ form.password.id_for_label }}">密码：</label>
		<div class="form-group">
			{{ form.password }}
		</div>
		<label for="{{ form.captcha.id_for_label }}">验证码：</label>
		<div class="form-group">
			{{ form.captcha }}
		</div>
		<input type="submit" class="btn btn-primary" value="登录">
		<small><a href="{% url 'user:forgot' %}">忘记密码</a></small>
		<div>还没有账号，<a href="{% url 'user:register' %}"><b><u>点击注册</u></b></a></div>
</form>
{% endblock main %}

user/templates/user/retakepassword.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
修改密码
{% endblock title %}

{% block main %}
<h1></h1>
<hr />
<form action="{% url 'user:retake-password' %}" method="post">
	<div class="form-group">
		<div class="form-group">
			{% csrf_token %}
		</div>
		<label for="{{ form.password.id_for_label }}">新密码：</label>
		<div class="form-group">
			{{ form.password }}
		</div>

		<label for="{{ form.password2.id_for_label }}">请再输入一次：</label>
		<div class="form-group">
			{{ form.password2 }}
		</div>

		<label for="{{ form.captcha.id_for_label }}">验证码：</label>
		<div class="form-group">
			{{ form.captcha }}
		</div>
		<input type="submit" class="btn btn-primary" value="提交">
</form>
{% endblock main %}

user/templates/user/signup.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
登录
{% endblock title %}

{% block main %}
<h1>注册</h1>
<hr />
<form action="{% url 'user:register' %}" method="post">
	<div class="form-group">
		<div class="form-group">
			{% csrf_token %}
		</div>
		<label for="{{ form.email.id_for_label }}">电子邮件：</label>
		<div class="form-group">
			{{ form.email }}
		</div>
		<label for="{{ form.username.id_for_label }}">用户名：</label>
		<div class="form-group">
			{{ form.username }}
		</div>
		<label for="{{ form.password.id_for_label }}">密码：</label>
		<div class="form-group">
			{{ form.password }}
		</div>
		<label for="{{ form.password2.id_for_label }}">请再输入一次：</label>
		<div class="form-group">
			{{ form.password2 }}
		</div>
		<input type="submit" class="btn btn-primary" value="加入我们">
</form>
{% endblock main %}